org: hossias
app: watchtower-api
service: watchtower-api
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: 'Allow'
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:us-east-1:789938723120:table/Data'
        - 'arn:aws:dynamodb:us-east-1:789938723120:table/Device'
        - 'arn:aws:dynamodb:us-east-1:789938723120:table/Network'

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - cors: true
    Variables:
      ACCESS_KEY_ID: AKIA3P3AELEYGUQL3GNI
      DATA_TABLE: Data
      DB_ENDPOINT: 'http://dynamodb.us-east-1.amazonaws.com'
      DEVICE_TABLE: Device
      NETWORK_TABLE: Network
      REGION: us-east-1
      SECRET_ACCESS_KEY: 4a1m9jZfCUvViG4W5YEjOJ6CIdsoV9zNwDecqSqW
      SERVER_PORT: '3001'
